kind: Namespace
apiVersion: v1
metadata:
  name: service-mesh-demo
  labels:
    istio-discovery: enabled
    istio-injection: enabled
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: users
  namespace: service-mesh-demo
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: user-profiles
  namespace: service-mesh-demo
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: users-v1
  labels:
    app.kubernetes.io/part-of: users
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'users:1.0.0'
  resources:
    limits:
      memory: 1Gi
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'openjdk-25:1.24-2.1773186581'
        namespace: openshift
  source:
    type: Git
    git:
      uri: 'https://github.com/mronconis/rhcl-demo.git'
    contextDir: apps/users-v1
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: users-v2
  labels:
    app.kubernetes.io/part-of: users
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'users:2.0.0'
  resources:
    limits:
      memory: 1Gi
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'openjdk-25:1.24-2.1773186581'
        namespace: openshift
  source:
    type: Git
    git:
      uri: 'https://github.com/mronconis/rhcl-demo.git'
    contextDir: apps/users-v2
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: user-profiles-v1
  labels:
    app.kubernetes.io/part-of: user-profiles
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'user-profiles:1.0.0'
  resources:
    limits:
      memory: 1Gi
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'openjdk-25:1.24-2.1773186581'
        namespace: openshift
  source:
    type: Git
    git:
      uri: 'https://github.com/mronconis/rhcl-demo.git'
    contextDir: apps/user-profiles-v1
