apiVersion: v1
kind: Secret
metadata:
  name: bob-key
  namespace: service-mesh-demo
  labels:
    authorino.kuadrant.io/managed-by: authorino
    app: users
  annotations:
    secret.kuadrant.io/user-id: bob
stringData:
  api_key: IAMBOB
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: alice-key
  namespace: service-mesh-demo
  labels:
    authorino.kuadrant.io/managed-by: authorino
    app: users
  annotations:
    secret.kuadrant.io/user-id: alice
stringData:
  api_key: IAMALICE
type: Opaque
---
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: users-auth
  namespace: service-mesh-demo
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: users-route-v2
  defaults:
   when:
     - predicate: "request.path != '/q/health'"
   rules:
    authentication:
      "api-key-users":
        apiKey:
          selector:
            matchLabels:
              app: users
        credentials:
          authorizationHeader:
            prefix: APIKEY

    metadata:
      "external-user-profile":
        http:
          url: "http://user-profiles-v1.service-mesh-demo.svc.cluster.local:8080/v1/user/profile"
          method: GET
          contentType: application/json
          headers:
            "x-user-id":
              expression: auth.identity.metadata.annotations["secret.kuadrant.io/user-id"]

    response:
      success:
        headers:
          "x-user-id":
            plain:
              expression: auth.identity.metadata.annotations["secret.kuadrant.io/user-id"]
          "x-user-role":
            plain:
              selector: auth.metadata.external-user-profile.role
          "x-user-department":
            plain:
              selector: auth.metadata.external-user-profile.department

  