apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: users-v1-rate-limit
  namespace: service-mesh-demo
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: users-route-v1
  limits:
    "global-limits-by-ip":
      rates:
      - limit: 3
        window: 1m
      counters:
      - expression: "auth.identity.source_ip"
---
apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: users-v2-rate-limit
  namespace: service-mesh-demo
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: users-route-v2
  limits:
    "global-limits-by-user_id":
      rates:
      - limit: 5
        window: 1m
      counters:
      - expression: "metadata.filter_metadata.envoy.filters.http.ext_authz.user_id"